trigger:
- main

pool:
  name: 'MvcMovie'

variables:
  buildConfiguration: 'Release'
  deployPath: 'C:\inetpub\wwwroot\MyApp'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- script: dotnet restore
  displayName: Restore

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build

- script: dotnet publish --configuration $(buildConfiguration) --framework netcoreapp3.1 --output $(Build.ArtifactStagingDirectory)
  displayName: Publish

- powershell: |
    Import-Module WebAdministration

    if (Get-Website -Name "default" -ErrorAction SilentlyContinue) {
        Stop-WebSite -Name "default"
    }

    Remove-Item "$(deployPath)\*" -Recurse -Force -ErrorAction SilentlyContinue

    Copy-Item "$(Build.ArtifactStagingDirectory)\*" "$(deployPath)" -Recurse

    if (-not (Get-Website -Name "default" -ErrorAction SilentlyContinue)) {
        New-Website -Name "default" -PhysicalPath "$(deployPath)" -Port 80
    }

    Start-WebSite -Name "default"

  displayName: Deploy to IIS
