trigger:
- main

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '3.1.x'

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    fetchDepth: 1

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '$(dotnetVersion)'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
      dotnet build --configuration $(buildConfiguration)
    displayName: 'Restore and Build'

  - script: |
      echo "Deploying application..."
    displayName: 'Deploy Application'
